// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvxNC_W6tJJ4IhKQgqyl14p9hERKpUllo',
    appId: '1:599603291720:web:9b1b2719da0e65104c5a7d',
    messagingSenderId: '599603291720',
    projectId: 'njangi-d69af',
    authDomain: 'njangi-d69af.firebaseapp.com',
    storageBucket: 'njangi-d69af.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc8PcegENvv0NShJ853RroIu2Zm1edjqY',
    appId: '1:599603291720:android:4dd960d9cf942f774c5a7d',
    messagingSenderId: '599603291720',
    projectId: 'njangi-d69af',
    storageBucket: 'njangi-d69af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDlKCgyYvvch66Oeopb3Z7HA1FioPUEuo',
    appId: '1:599603291720:ios:092da352f6339d874c5a7d',
    messagingSenderId: '599603291720',
    projectId: 'njangi-d69af',
    storageBucket: 'njangi-d69af.firebasestorage.app',
    iosBundleId: 'com.example.njangui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDlKCgyYvvch66Oeopb3Z7HA1FioPUEuo',
    appId: '1:599603291720:ios:092da352f6339d874c5a7d',
    messagingSenderId: '599603291720',
    projectId: 'njangi-d69af',
    storageBucket: 'njangi-d69af.firebasestorage.app',
    iosBundleId: 'com.example.njangui',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvxNC_W6tJJ4IhKQgqyl14p9hERKpUllo',
    appId: '1:599603291720:web:dd57427c82451c7f4c5a7d',
    messagingSenderId: '599603291720',
    projectId: 'njangi-d69af',
    authDomain: 'njangi-d69af.firebaseapp.com',
    storageBucket: 'njangi-d69af.firebasestorage.app',
  );
}
